name: advanced
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.2

environment:
  sdk: ^3.7.0

dependencies:
  dio: ^5.8.0+1
  easy_localization: ^3.0.7+1
  firebase_core: ^3.12.1
  flutter:
    sdk: flutter
  flutter_bloc: ^9.0.0
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.4.5
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.0.17
  freezed_annotation: ^2.4.1
  get_it: ^8.0.3
  intl: ^0.19.0
  json_annotation: ^4.9.0
  pretty_dio_logger: ^1.4.0
  retrofit: ^4.4.2
  retrofit_generator: ^9.1.9
  

dev_dependencies:
  build_runner: ^2.4.15
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.4.5
  json_serializable: ^6.9.4

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/svgs/
flutter_intl:
  enabled: true
