name: advanced
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  dio: ^5.8.0+1
  easy_localization: ^3.0.7+1
  flutter:
    sdk: flutter
  flutter_bloc: ^9.0.0
  flutter_native_splash: ^2.4.5
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.0.17
  freezed: ^3.0.0
  freezed_annotation: ^3.0.0
  get_it: ^8.0.3
  intl: ^0.19.0
  json_annotation: ^4.9.0
  json_serializable: ^6.9.4
  pretty_dio_logger: ^1.4.0
  retrofit: ^4.4.2
  retrofit_generator: ^9.1.9

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/svgs/
